CREATE TABLE IF NOT EXISTS emailjs_quota (
    id TINYINT UNSIGNED PRIMARY KEY,
    remaining_requests SMALLINT UNSIGNED NOT NULL,
    cycle_limit SMALLINT UNSIGNED NOT NULL,
    reset_at_utc DATETIME NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;